### ISSUE TITLE
Logrus changed to lower case, pkg now duplicated in vendor directory.

### ISSUE THREAD

**Issue by bweston92** [jessfraz/amicontained#2]
Logrus went lower case https://github.com/sirupsen/logrus/pull/384

The issue is there is now 2 directories in vendor folder.
- amicontained//vendor/github.com/Sirupsen/logrus
- amicontained//vendor/github.com/sirupsen/logrus

**Comment by jessfraz** [comment]
wanna make a PR to clean it up
